# Dependencies
markdown:   kramdown
highlighter:    pygments

# Permalinks
relative_permalinks:    false
permalink:  pretty

# Setup
title:  GNA
tagline:    'The Geographic Network Analysis Project'
description:    'The GNA Project'
baseurl:    /gna_project

author:
  name: 'João Ponce de Leão'
  url:  http://ponceleao.com

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:
