# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            GNA
tagline:          'The GNA Project'
description:      'The Geographic Network Analysis Project'
baseurl:          /GNA_public

author:
  name:           'João Ponce de Leão'
  url:            https://ponceleao.com

paginate:         5
